apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib-app
  template:
    metadata:
      labels:
        app: fib-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: fib
        image: fibimg
        imagePullPolicy: Never
        command: ["/app/fib"]
        args: ["10"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
          name: metrics