replicaCount: 2

image:
  repository: ${{ secrets.DOCKERHUB_USERNAME }}/ci_cd
  tag: "1.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"