name: Check
on:
    push:
      branches: [ ci_cd_test ]
    workflow_dispatch:
    pull_request:
      branches: [ ci_cd_test ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Start build
            run: ./scripts/build.sh

          - name: Run test
            run: ./scripts/test.sh

          - name: Build deb pack
            run: .scripts/package.sh