name: Package

on: push

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building deb
        run: ./scripts/package.sh